const CONFIG = {
    introTitle: 'Alooo, em Cá đấy à!',
    introDesc: `Hôm nay lại bỏ bữa chứ gì ?`,
    btnIntro: '-.-',
    title: 'Không biết Cá đang làm gì ta ?',
    desc: 'Làm gì ấy nhờ',
    btnYes: 'Cá đang làm việc',
    btnNo: 'Cá đang cườiiiii ',
    question:'Thèm bún đậu hongg ?',
    btnReply: 'Chắc cũng đang thèm đây mà :))',
    reply: 'Thèm thì thèm mà không thèm vẫn phải thèm :))',
    mess: 'Không xàm xí nữa đâu, Cá để ý sức khoẻ nhá',
    messDesc: 'Chúc Cá một kì nghỉ lễ siêu vui ha',
    btnAccept: 'Have a good night <3',
    messLink: 'https://www.instagram.com/a_p.th/'
